"""
SQL validation and safety layer.

This module validates SQL generated by the LLM before
it is allowed to reach the database.
"""

from dataclasses import dataclass, field

import sqlglot
from sqlglot import exp


@dataclass
class ValidationResult:
    """
    Stores the result of SQL validation.
    """

    is_valid: bool
    sql: str
    error: str | None = None
    tables_used: list[str] = field(default_factory=list)
    warnings: list[str] = field(default_factory=list)


class SQLValidator:
    """
    Validates LLM-generated SQL before database execution.

    The validator currently enforces:

    - Exactly one SQL statement
    - SELECT queries only
    - No INSERT, UPDATE, DELETE, DROP, ALTER, etc.
    - Only known database tables can be accessed
    - SQLite-compatible SQL syntax
    """

    ALLOWED_TABLES = {
        "customers",
        "orders",
        "order_items",
        "payments",
        "reviews",
        "products",
        "sellers",
        "geolocation",
        "category_translation",
    }

    BLOCKED_KEYWORDS = {
        "INSERT",
        "UPDATE",
        "DELETE",
        "DROP",
        "ALTER",
        "CREATE",
        "TRUNCATE",
        "ATTACH",
        "DETACH",
        "PRAGMA",
        "REPLACE",
        "VACUUM",
    }

    def validate(self, sql: str) -> ValidationResult:
        """
        Validate a SQL query.

        Parameters
        ----------
        sql:
            SQL generated by the LLM.

        Returns
        -------
        ValidationResult
            Structured validation result.
        """

        if not sql or not sql.strip():
            return ValidationResult(
                is_valid=False,
                sql=sql,
                error="SQL query is empty.",
            )

        cleaned_sql = sql.strip()

        # Remove a trailing semicolon for easier processing.
        cleaned_sql = cleaned_sql.rstrip(";").strip()

        # ---------------------------------------------------------
        # 1. Basic keyword safety check
        # ---------------------------------------------------------

        upper_sql = cleaned_sql.upper()

        for keyword in self.BLOCKED_KEYWORDS:
            if self._contains_keyword(upper_sql, keyword):
                return ValidationResult(
                    is_valid=False,
                    sql=cleaned_sql,
                    error=f"Blocked SQL operation detected: {keyword}",
                )

        # ---------------------------------------------------------
        # 2. Parse SQL using SQLGlot
        # ---------------------------------------------------------

        try:
            statements = sqlglot.parse(
                cleaned_sql,
                read="sqlite",
            )
        except Exception as exc:
            return ValidationResult(
                is_valid=False,
                sql=cleaned_sql,
                error=f"SQL parsing failed: {exc}",
            )

        # ---------------------------------------------------------
        # 3. Only one statement is allowed
        # ---------------------------------------------------------

        if len(statements) != 1:
            return ValidationResult(
                is_valid=False,
                sql=cleaned_sql,
                error="Multiple SQL statements are not allowed.",
            )

        parsed_sql = statements[0]

        # ---------------------------------------------------------
        # 4. Only SELECT queries are allowed
        # ---------------------------------------------------------

        if not self._is_read_only_query(parsed_sql):
            return ValidationResult(
                is_valid=False,
                sql=cleaned_sql,
                error="Only SELECT queries are allowed.",
            )

        # ---------------------------------------------------------
        # 5. Find tables used by the query
        # ---------------------------------------------------------

        tables_used = self._extract_tables(parsed_sql)

        unknown_tables = [
            table
            for table in tables_used
            if table.lower() not in self.ALLOWED_TABLES
        ]

        if unknown_tables:
            return ValidationResult(
                is_valid=False,
                sql=cleaned_sql,
                tables_used=tables_used,
                error=(
                    "Query references unknown table(s): "
                    + ", ".join(unknown_tables)
                ),
            )

        # ---------------------------------------------------------
        # 6. Validation successful
        # ---------------------------------------------------------

        return ValidationResult(
            is_valid=True,
            sql=cleaned_sql,
            tables_used=tables_used,
        )

    def _contains_keyword(self, sql: str, keyword: str) -> bool:
        """
        Check whether a SQL keyword appears as a separate word.

        This prevents matching something like:

            created_at

        when looking for:

            CREATE
        """

        import re

        pattern = rf"\b{re.escape(keyword)}\b"

        return bool(re.search(pattern, sql))

    def _is_read_only_query(self, parsed_sql: exp.Expression) -> bool:
        """
        Determine whether the parsed query is read-only.
        """

        # SELECT and WITH ... SELECT queries are allowed.
        if isinstance(parsed_sql, (exp.Select, exp.Union)):
            return True

        # SQLGlot represents WITH queries as expressions
        # containing a SELECT body.
        if isinstance(parsed_sql, exp.Query):
            return True

        return False

    def _extract_tables(self, parsed_sql: exp.Expression) -> list[str]:
        """
        Extract all table names referenced by the SQL query.
        """

        tables = set()

        for table in parsed_sql.find_all(exp.Table):
            table_name = table.name

            if table_name:
                tables.add(table_name)

        return sorted(tables)